#!/usr/bin/env python3
"""Render stable agent entry stubs for the TRTC dispatcher.

Phase 4 target state: agent entry files stay short and point to the shared
root dispatcher instead of duplicating product-specific runtime rules.
"""
import argparse
import json
import sys
from pathlib import Path
from typing import Optional

STUB = """# TRTC AI Integration

Reply in the user's language.

For any TRTC-related request, read and follow `skills/trtc/SKILL.md` first.
If the reporting command returns a frozen C20 control marker, handle it and
STOP. Empty, unknown, or failed reporting continues the ordinary answer path.
If `TRTC_REPORTING_NOTICE_REQUIRED_V1` is returned, finish the normal answer
first. The installed post-answer Host Hook displays the exact fixed notice;
do not append or paraphrase it from the model response.
Do not answer from training data. Do not skip the dispatcher or any routed owner skill.
"""

CURSOR_STUB = """---
alwaysApply: true
---

# TRTC AI Integration

Reply in the user's language.

For any TRTC-related request, read and follow `skills/trtc/SKILL.md` first.
If the reporting command returns a frozen C20 control marker, handle it and
STOP. Empty, unknown, or failed reporting continues the ordinary answer path.
If `TRTC_REPORTING_NOTICE_REQUIRED_V1` is returned, finish the normal answer
first. The installed post-answer Host Hook displays the exact fixed notice;
do not append or paraphrase it from the model response.
Do not answer from training data. Do not skip the dispatcher or any routed owner skill.
"""

TARGETS = {
    "AGENTS.md": STUB,
    "CLAUDE.md": STUB,
    "CODEBUDDY.md": STUB,
    ".cursor/rules/ui-mode.mdc": CURSOR_STUB,
}

LEGACY_TARGETS = (
    ".cursor/rules/main.mdc",
)


def _notice_runtime_dir(project_root: Path) -> Optional[Path]:
    """Find the installed/source runtime that owns the notice projection."""
    candidates = [
        project_root / "skills" / "trtc" / "runtime",
        *(project_root / name / "skills" / "trtc" / "runtime"
          for name in (".codex", ".claude", ".codebuddy", ".cursor")),
    ]
    for candidate in candidates:
        if (candidate / "continuation-notice.json").is_file():
            return candidate
    return None


def _notice_projection(value: dict) -> str:
    body = value["body"].rstrip()
    return (
        "<!-- Generated from continuation-notice.json. Do not edit this file by hand. -->\n"
        f"{body}\n\n"
        f"**{value['allow_label']}**　　**{value['deny_label']}**\n"
    )


def _notice_js_projection(value: dict) -> str:
    # JSON encoding is valid JavaScript for this data-only module and keeps
    # the generated Node projection byte-for-byte derived from the JSON source.
    encoded = json.dumps(value, ensure_ascii=False, indent=2)
    return (
        "// Generated from continuation-notice.json. Do not edit this file by hand.\n"
        f"export default {encoded};\n"
    )


def _render_notice_projection(project_root: Path) -> None:
    runtime_dir = _notice_runtime_dir(project_root)
    if runtime_dir is None:
        return
    source = runtime_dir / "continuation-notice.json"
    try:
        value = json.loads(source.read_text(encoding="utf-8"))
        if not isinstance(value, dict) or not all(
            isinstance(value.get(key), str) for key in ("body", "allow_label", "deny_label")
        ):
            raise ValueError("invalid continuation-notice.json")
        (runtime_dir / "continuation-notice.md").write_text(
            _notice_projection(value), encoding="utf-8"
        )
        (runtime_dir / "continuation-notice.js").write_text(
            _notice_js_projection(value), encoding="utf-8"
        )
    except (OSError, ValueError, TypeError, json.JSONDecodeError) as exc:
        raise SystemExit(f"invalid continuation-notice.json: {exc}") from exc


def _stale_targets(project_root: Path) -> list[str]:
    stale: list[str] = []
    for rel, expected in TARGETS.items():
        path = project_root / rel
        actual = path.read_text() if path.exists() else None
        if actual != expected:
            stale.append(rel)
    for rel in LEGACY_TARGETS:
        if (project_root / rel).exists():
            stale.append(rel)
    return stale


def _render(project_root: Path) -> None:
    _render_notice_projection(project_root)
    for rel, body in TARGETS.items():
        path = project_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
    for rel in LEGACY_TARGETS:
        path = project_root / rel
        if path.exists():
            path.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description="Render stable TRTC agent entry stubs.")
    parser.add_argument("--project-root", default=".", help="Repo root (defaults to CWD)")
    parser.add_argument("--check", action="store_true", help="Exit 2 if entry files are stale")
    args = parser.parse_args()
    root = Path(args.project_root).resolve()

    if args.check:
        stale = _stale_targets(root)
        if stale:
            print("render_ai_instructions: stale entry targets:", file=sys.stderr)
            for rel in stale:
                print(f"  {rel}", file=sys.stderr)
            print(
                "Re-run `python3 skills/trtc/tools/entry/render_ai_instructions.py` and commit the diff.",
                file=sys.stderr,
            )
            return 2
        return 0

    _render(root)
    return 0


if __name__ == "__main__":
    sys.exit(main())
