/*
* Copyright (c) 2025 Tencent
* All rights reserved.
*
* Author: eddardliu
*/

import {
	AlbumMedia,
	AlbumMediaType,
	AlbumPickerConfig,
	AlbumPickerTheme,
} from '../AlbumPicker'

export class AlbumPickerImpl {
	serializeConfig(config?: AlbumPickerConfig | null): UTSJSONObject {
		return {
			pickMode: config?.mediaFilter ?? null,
			maxCount: config?.maxSelectionCount ?? null,
			gridCount: config?.itemsPerRow ?? null,
			showsCameraItem: config?.showsCameraItem ?? null,
			style: config?.style ?? null,
			language: config?.language ?? null,
			compressQuality: config?.compressQuality ?? null,
			maxVideoDurationInSeconds: config?.maxVideoDurationInSeconds ?? null,
			maxOutputFileSizeInMB: config?.maxOutputFileSizeInMB ?? null,
		}
	}

	serializeTheme(theme?: AlbumPickerTheme | null): UTSJSONObject {
		return {
			primaryColor: theme?.primaryColor ?? null,
			backgroundColor: theme?.backgroundColor ?? null,
			backgroundColorSecondary: theme?.backgroundColorSecondary ?? null,
			textColor: theme?.textColor ?? null,
			textColorSecondary: theme?.textColorSecondary ?? null,
			confirmButtonIconAsset: theme?.confirmButtonIconAsset ?? null,
			bigFontSize: theme?.bigFontSize ?? null,
			normalFontSize: theme?.normalFontSize ?? null,
			smallFontSize: theme?.smallFontSize ?? null,
			bigRadius: theme?.bigRadius ?? null,
			normalRadius: theme?.normalRadius ?? null,
			smallRadius: theme?.smallRadius ?? null,
		}
	}

	static parseAlbumMedia(data: any): AlbumMedia {
		const d: UTSJSONObject = (data ?? new UTSJSONObject()) as UTSJSONObject
		const idRaw: any | null = d['id']
		const mediaTypeRaw: any | null = d['mediaType']
		const mediaPathRaw: any | null = d['mediaPath']
		const fileExtensionRaw: any | null = d['fileExtension']
		const fileSizeRaw: any | null = d['fileSize']
		const videoThumbnailPathRaw: any | null = d['videoThumbnailPath']
		const durationRaw: any | null = d['duration']
		return {
			id: typeof idRaw == 'number' ? idRaw as number : 0,
			mediaType: (typeof mediaTypeRaw == 'number' ? mediaTypeRaw as number : 0) == 1 ? AlbumMediaType.VIDEO : AlbumMediaType.IMAGE,
			mediaPath: typeof mediaPathRaw == 'string' ? mediaPathRaw as string : '',
			fileExtension: typeof fileExtensionRaw == 'string' ? fileExtensionRaw as string : '',
			fileSize: typeof fileSizeRaw == 'number' ? fileSizeRaw as number : 0,
			videoThumbnailPath: typeof videoThumbnailPathRaw == 'string' ? videoThumbnailPathRaw as string : '',
			duration: typeof durationRaw == 'number' ? durationRaw as number : 0,
		}
	}

	static parseAlbumMediaList(dataList: any[]): AlbumMedia[] {
		const out: AlbumMedia[] = []
		for (let i: number = 0; i < dataList.length; i++) {
			out.push(AlbumPickerImpl.parseAlbumMedia(dataList[i] as any))
		}
		return out
	}
}
